canny:
     process: CannyDetector
     input:
     -    attr: Slider
          args:
               label: low_threshold
               minimum: 1
               maximum: 255
               value: 100
               step: 1
     -    attr: Slider
          args:
               label: high_threshold
               minimum: 1
               maximum: 255
               value: 200
               step: 1
hed:
     process: HedDetector
     input: []
mlsd:
     process: MLSDProcessor
     input:
     -    attr: Slider
          args:
               label: value_threshold
               minimum: 0.01
               maximum: 2.0
               value: 0.1
               step: 0.01
     -    attr: Slider
          args:
               label: distance_threshold
               minimum: 0.01
               maximum: 20.0
               value: 0.1
               step: 0.01
midas:
     process: MidasProcessor
     input:
     -    attr: Slider
          args:
               label: alpha
               minimum: 0.1
               maximum: 20
               value: 6.2
               step: 0.01
openpose:
     process: OpenposeDetector
     input:
     -    attr: Checkbox
          args:
               label: detect hand
               value: false
uniformer:
     process: UniformerDetector
     input: []
lineArt:
     process: LineArtDetector
     input: []
lineArtAnime:
     process: LineArtAnimeDetector
     input: []
mangaLine:
     process: MangaLineExtration
normalBae:
     process: NormalBaeDetector
leres:
     process: LeresPix2Pix
     input:
     -    attr: Slider
          args:
               label: thr_a
               minimum: 0
               maximum: 250
               value: 100
               step: 1
     -    attr: Slider
          args:
               label: thr_b
               minimum: 0
               maximum: 250
               value: 200
               step: 1
     -    attr: Checkbox
          args:
               label: boost
               value: false
meidaPipe:
     process: MediaPipeFace
     input:
     -    attr: Slider
          args:
               label: max_faces
               minimum: 1
               maximum: 100
               value: 1
               step: 1
     -    attr: Slider
          args:
               label: min_confidence
               minimum: 0
               maximum: 1
               value: 0.5
               step: 0.1
pidinet:
     process: PidInet
     input:
     -    attr: Checkbox
          args:
               label: is_safe
               value: false
     -    attr: Checkbox
          args:
               label: apply_fliter
               value: false
shuffle:
     process: Image2MaskShuffleDetector
     input: []
zoe:
     process: ZoeDetector
     input: []
oneformer:
     process: OneformerDetector
     input: []
